#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-janitor
Version  : 1.1.1
Release  : 3
URL      : https://cran.r-project.org/src/contrib/janitor_1.1.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/janitor_1.1.1.tar.gz
Summary  : Simple Tools for Examining and Cleaning Dirty Data
Group    : Development/Tools
License  : MIT
Requires: R-dplyr
Requires: R-pkgconfig
Requires: R-purrr
Requires: R-snakecase
Requires: R-tidyr
BuildRequires : R-dplyr
BuildRequires : R-pkgconfig
BuildRequires : R-purrr
BuildRequires : R-snakecase
BuildRequires : R-tidyr
BuildRequires : buildreq-R

%description
names; provide quick counts of variable combinations (i.e., frequency
    tables and crosstabs); and isolate duplicate records. Other janitor functions
    nicely format the tabulation results. These tabulate-and-report functions
    approximate popular features of SPSS and Microsoft Excel. This package
    follows the principles of the "tidyverse" and works well with the pipe function
    %>%. janitor was built with beginning-to-intermediate R users in mind and is
    optimized for user-friendliness. Advanced R users can already do everything
    covered here, but with janitor they can do it faster and save their thinking for
    the fun stuff.

%prep
%setup -q -c -n janitor

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533072656

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1533072656
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library janitor
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library janitor
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library janitor
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library janitor|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/janitor/DESCRIPTION
/usr/lib64/R/library/janitor/INDEX
/usr/lib64/R/library/janitor/LICENSE
/usr/lib64/R/library/janitor/Meta/Rd.rds
/usr/lib64/R/library/janitor/Meta/features.rds
/usr/lib64/R/library/janitor/Meta/hsearch.rds
/usr/lib64/R/library/janitor/Meta/links.rds
/usr/lib64/R/library/janitor/Meta/nsInfo.rds
/usr/lib64/R/library/janitor/Meta/package.rds
/usr/lib64/R/library/janitor/Meta/vignette.rds
/usr/lib64/R/library/janitor/NAMESPACE
/usr/lib64/R/library/janitor/NEWS.md
/usr/lib64/R/library/janitor/R/janitor
/usr/lib64/R/library/janitor/R/janitor.rdb
/usr/lib64/R/library/janitor/R/janitor.rdx
/usr/lib64/R/library/janitor/doc/index.html
/usr/lib64/R/library/janitor/doc/introduction.R
/usr/lib64/R/library/janitor/doc/introduction.Rmd
/usr/lib64/R/library/janitor/doc/introduction.html
/usr/lib64/R/library/janitor/doc/janitor.R
/usr/lib64/R/library/janitor/doc/janitor.Rmd
/usr/lib64/R/library/janitor/doc/janitor.html
/usr/lib64/R/library/janitor/doc/tabyls.R
/usr/lib64/R/library/janitor/doc/tabyls.Rmd
/usr/lib64/R/library/janitor/doc/tabyls.html
/usr/lib64/R/library/janitor/help/AnIndex
/usr/lib64/R/library/janitor/help/aliases.rds
/usr/lib64/R/library/janitor/help/figures/logo_small.png
/usr/lib64/R/library/janitor/help/janitor.rdb
/usr/lib64/R/library/janitor/help/janitor.rdx
/usr/lib64/R/library/janitor/help/paths.rds
/usr/lib64/R/library/janitor/html/00Index.html
/usr/lib64/R/library/janitor/html/R.css
